apiVersion: apps/v1
kind: Deployment
metadata:
  name: handle-payment
  namespace: bidly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: handle-payment
  template:
    metadata:
      labels:
        app: handle-payment
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command: ["sh", "-c", "until nc -z rabbitmq 5672; do echo waiting for rabbitmq; sleep 5; done; echo rabbitmq port open, sleeping 20s for readiness; sleep 20"]
      containers:
        - name: handle-payment
          image: asia-southeast1-docker.pkg.dev/project-0ccd7e90-483b-4e7d-904/bidly/handle-payment:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8012
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
          envFrom:
            - secretRef:
                name: stripe-secret
