apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: bidly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: asia-southeast1-docker.pkg.dev/project-0ccd7e90-483b-4e7d-904/bidly/payment:65f084b49cd2e61fab86a4f06fa4cb86c9187e10
          imagePullPolicy: Always
          ports:
            - containerPort: 8011
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
          envFrom:
            - secretRef:
                name: stripe-secret
            - configMapRef:
                name: bidly-config
