volumes:

networks:
  bidly-net:
    driver: bridge
    name: bidly-net

services:
  tasks:
    build: ./backend/services/tasks
    container_name: tasks
    ports:
      - "8000:8000"
    networks:
      - bidly-net
    env_file:
      - .env

  chats:
    build: ./backend/services/chats
    container_name: chats
    ports:
      - "8001:8001"
    networks:
      - bidly-net
    env_file:
      - .env