apiVersion: apps/v1
kind: Deployment
metadata:
  name: bids
  namespace: bidly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bids
  template:
    metadata:
      labels:
        app: bids
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command: ["sh", "-c", "until nc -z rabbitmq 5672; do echo waiting for rabbitmq; sleep 5; done; echo rabbitmq port open, sleeping 20s for readiness; sleep 20"]
        - name: wait-for-redis
          image: busybox
          command: ["sh", "-c", "until nc -z redis 6379; do sleep 3; done"]
      containers:
        - name: bids
          image: asia-southeast1-docker.pkg.dev/project-0ccd7e90-483b-4e7d-904/bidly/bids:ccd238b30be25259372af434bb26e6e656ab745c
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
          envFrom:
            - secretRef:
                name: supabase-secret

