apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bidly-ingress
  namespace: bidly
spec:
  ingressClassName: gce
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kong
                port:
                  number: 8000
