apiVersion: apps/v1
kind: Deployment
metadata:
  name: send-notification
  namespace: bidly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: send-notification
  template:
    metadata:
      labels:
        app: send-notification
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command: ["sh", "-c", "until nc -z rabbitmq 5672; do echo waiting for rabbitmq; sleep 5; done; echo rabbitmq port open, sleeping 20s for readiness; sleep 20"]
      containers:
        - name: send-notification
          image: asia-southeast1-docker.pkg.dev/project-0ccd7e90-483b-4e7d-904/bidly/send-notifications:ac8150f8374c9db5f117e5b1d9b7df06fbc90b65
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
