apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks
  namespace: bidly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: asia-southeast1-docker.pkg.dev/project-0ccd7e90-483b-4e7d-904/bidly/tasks:7192f21f89daf70a6914498dec959df18a6b7ec1
          imagePullPolicy: Always
          ports:
            - containerPort: 8005
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
          envFrom:
            - secretRef:
                name: supabase-secret
