apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-task
  namespace: bidly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: create-task
  template:
    metadata:
      labels:
        app: create-task
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command: ["sh", "-c", "until nc -z rabbitmq 5672; do echo waiting for rabbitmq; sleep 5; done; echo rabbitmq port open, sleeping 20s for readiness; sleep 20"]
      containers:
        - name: create-task
          image: asia-southeast1-docker.pkg.dev/project-0ccd7e90-483b-4e7d-904/bidly/create-task:2537e5841bc50a274b8b858ec610628ccb86bc9d
          imagePullPolicy: Always
          ports:
            - containerPort: 8009
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
          envFrom:
            - secretRef:
                name: supabase-secret
