apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: bidly
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: asia-southeast1-docker.pkg.dev/project-0ccd7e90-483b-4e7d-904/bidly/users:latest
          ports:
            - containerPort: 8004
          envFrom:
            - secretRef:
                name: supabase-secret
