apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications
  namespace: bidly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - name: notifications
          image: asia-southeast1-docker.pkg.dev/project-0ccd7e90-483b-4e7d-904/bidly/notifications:latest
          ports:
            - containerPort: 8008
          envFrom:
            - secretRef:
                name: sendgrid-secret
