apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect-chat
  namespace: bidly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connect-chat
  template:
    metadata:
      labels:
        app: connect-chat
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command: ["sh", "-c", "until nc -z rabbitmq 5672; do echo waiting for rabbitmq; sleep 5; done; echo rabbitmq port open, sleeping 20s for readiness; sleep 20"]
      containers:
        - name: connect-chat
          image: asia-southeast1-docker.pkg.dev/project-0ccd7e90-483b-4e7d-904/bidly/connect-chat:a7ebb97a8009992382d07e304eeccbefee00f5bf
          imagePullPolicy: Always
          ports:
            - containerPort: 8010
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
          envFrom:
            - secretRef:
                name: supabase-secret
