apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kong
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - bidly
  selector:
    matchLabels:
      app: kong
  endpoints:
    - port: admin
      path: /metrics
      interval: 15s
