apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket
  namespace: bidly
spec:
  replicas: 2
  selector:
    matchLabels:
      app: websocket
  template:
    metadata:
      labels:
        app: websocket
    spec:
      containers:
        - name: websocket
          image: asia-southeast1-docker.pkg.dev/project-0ccd7e90-483b-4e7d-904/bidly/websocket:latest
          ports:
            - containerPort: 8007
          # RabbitMQ hostname "rabbitmq" is hardcoded in the service, matches k8s Service name
